# =========================================================================
# UCT Micromouse - PikaScript Hardware Interface
# =========================================================================
# The Rust pre-compiler reads this file and generates 'uct_mouse.h'.
# This replaces the TCP mock wrapper when running natively on the silicon!
# =========================================================================

def init() -> int: ...
def set_motors(left_pwm: int, right_pwm: int): ...
def get_tof() -> tuple: ...
def get_encoders() -> tuple: ...
def get_gyro() -> float: ...
def get_vbatt() -> float: ...
def delay_ms(ms: int): ...
def set_polarity(left_polarity: int, right_polarity: int): ...