% MATLAB script to add the MATLAB Function block to StudentTemplate.slx
try
    disp('>> Loading StudentTemplate.slx...');
    load_system('StudentTemplate');
    
    block_name = 'StudentTemplate/Micromouse_Controller';
    
    % Delete existing controller block if it exists to overwrite it cleanly
    if ~isempty(find_system('StudentTemplate', 'SearchDepth', 1, 'Name', 'Micromouse_Controller'))
        disp('>> Overwriting existing Micromouse_Controller block...');
        delete_block(block_name);
    end
    
    disp('>> Adding MATLAB Function block...');
    h = add_block('simulink/User-Defined Functions/MATLAB Function', block_name);
    set_param(h, 'Position', [400, 220, 650, 480]);
    
    % Configure the internal script for the MATLAB Function block using Stateflow API
    disp('>> Configuring block ports and code template...');
    rt = sfroot;
    mfn = rt.find('-isa', 'Stateflow.EMChart', 'Path', 'StudentTemplate/Micromouse_Controller');
    
    if isempty(mfn)
        error('Could not retrieve Stateflow chart for MATLAB Function block.');
    end
    
    mfn.Script = sprintf([ ...
        'function [motor_l, motor_r, led0, led1, led2, state, oled_h, oled_1, oled_2, oled_3, oled_4] = loop(tof_l, tof_c, tof_r, lenc, renc, gyro, vbatt, sw1, sw2)\n' ...
        '    %% UCT MICROMOUSE - STUDENT CONTROLLER LOOP\n' ...
        '    %%\n' ...
        '    %% Inputs:\n' ...
        '    %%   tof_l, tof_c, tof_r : Left, Center, Right ToF values (uint16, mm)\n' ...
        '    %%   lenc, renc          : Wheel encoder delta ticks since last step (int32)\n' ...
        '    %%   gyro                : Yaw-rate gyroscope reading (single, deg/s)\n' ...
        '    %%   vbatt               : Battery voltage (single, V)\n' ...
        '    %%   sw1, sw2            : Button states (uint8, 0 or 1)\n' ...
        '    %%\n' ...
        '    %% Outputs:\n' ...
        '    %%   motor_l, motor_r    : Motor PWM command values (int16, -100 to 100)\n' ...
        '    %%   led0, led1, led2    : LED output states (uint8, 0 or 1)\n' ...
        '    %%   state               : Control state to report (int16)\n' ...
        '    %%   oled_h              : 10-char header string for OLED display\n' ...
        '    %%   oled_1..4           : 20-char line strings for OLED display\n' ...
        '\n' ...
        '    persistent current_state;\n' ...
        '    if isempty(current_state)\n' ...
        '        current_state = int16(0);\n' ...
        '    end\n' ...
        '\n' ...
        '    %% Default outputs\n' ...
        '    led0 = uint8(0);\n' ...
        '    led1 = uint8(0);\n' ...
        '    led2 = uint8(0);\n' ...
        '    state = current_state;\n' ...
        '    \n' ...
        '    oled_h = ''UCT MOUSE'';\n' ...
        '    oled_1 = ''SYSTEM READY'';\n' ...
        '    oled_2 = [''ToF C: '' num2str(tof_c) '' mm''];\n' ...
        '    oled_3 = [''L: '' num2str(tof_l) '' R: '' num2str(tof_r)];\n' ...
        '    oled_4 = ''CLICK RUN'';\n' ...
        '\n' ...
        '    %% Simple navigation logic example:\n' ...
        '    if tof_c < 150\n' ...
        '        %% Wall ahead: Turn right in place\n' ...
        '        motor_l = int16(30);\n' ...
        '        motor_r = int16(-30);\n' ...
        '        led0 = uint8(1);\n' ...
        '        oled_1 = ''TURNING RIGHT'';\n' ...
        '    else\n' ...
        '        %% Path clear: Drive straight\n' ...
        '        motor_l = int16(40);\n' ...
        '        motor_r = int16(40);\n' ...
        '        oled_1 = ''DRIVING FORWARD'';\n' ...
        '    end\n' ...
        'end\n' ...
    ]);
    
    disp('>> Saving StudentTemplate.slx...');
    save_system('StudentTemplate');
    disp('>> Success! Pre-configured controller block added to StudentTemplate.slx.');
catch ME
    fprintf('>> Error occurred: %s\n', ME.message);
end
