% Helper script to configure models for auto-flashing on build and simulation cleanups
models = {'StudentTemplate', 'StudentTemplate_matlabfunc', 'UCT_KDeploy', 'StudentTemplate_minimal', 'milestone1_square', 'milestone2_maze'};
for i = 1:length(models)
    model = models{i};
    try
        load_system(model);
        set_param(model, 'PostCodeGenCommand', 'flash_micromouse(buildInfo)');
        start_cmd = [ ...
            'fid = fopen(''/Users/nicolls/proj/eee3097s/2026/UCT-Micromouse/matlab_callbacks.log'', ''a''); ' ...
            'if fid ~= -1, fprintf(fid, ''%s: StartFcn triggered\n'', datestr(now)); fclose(fid); end; ' ...
            'run(''/Users/nicolls/proj/eee3097s/2026/UCT-Micromouse/matlab/simulink/launch_virtual_testbed.m''); ' ...
        ];
        set_param(model, 'StartFcn', start_cmd);
        
        stop_cmd = [ ...
            'fid = fopen(''/Users/nicolls/proj/eee3097s/2026/UCT-Micromouse/matlab_callbacks.log'', ''a''); ' ...
            'if fid ~= -1, fprintf(fid, ''%s: StopFcn triggered\n'', datestr(now)); fclose(fid); end; ' ...
            'clear mex; clear functions; ' ...
            'if ~ispc, ' ...
            '[~, ~] = system(''/usr/bin/pkill -f ''''[p]hysics_sim.py'''' ''); ' ...
            'else, ' ...
            '[~, ~] = system(''powershell -Command \"Get-CimInstance Win32_Process -Filter \\\"CommandLine like ''''%physics_sim.py%''''\\\" | Invoke-CimMethod -MethodName Terminate\" >nul 2>&1''); ' ...
            'end' ...
        ];
        set_param(model, 'StopFcn', stop_cmd);
        save_system(model);
        fprintf('Configured %s.slx to auto-flash on build and terminate simulator on stop.\n', model);
    catch ME
        fprintf('Failed to configure %s: %s\n', model, ME.message);
    end
end
