#ifndef STUDENT_CODE_H
#define STUDENT_CODE_H
const char* student_python_code = 
"# =========================================================================\n"
"# UCT Micromouse - Milestone 1: Run a Square (1m x 1m) (Framework)\n"
"# =========================================================================\n"
"# ASSIGNMENT DESCRIPTION:\n"
"# Implement a control loop to drive the mouse in a 1 meter by 1 meter square,\n"
"# turning 90 degrees at each corner, and returning to the start position.\n"
"# \n"
"# KEY CONTROLS:\n"
"# - uct_mouse.set_motors(left_pwm, right_pwm) -> Set speed (-100 to 100)\n"
"# - uct_mouse.get_encoders() -> Returns (left_ticks, right_ticks)\n"
"# - uct_mouse.get_tof()      -> Returns (left_mm, center_mm, right_mm)\n"
"# - uct_mouse.delay_ms(ms)   -> Suspends execution and updates sensors\n"
"#\n"
"# GRADING:\n"
"# - The autograder applies 8% motor imbalance and 8% wheel slip.\n"
"# - Open-loop timing alone will accumulate errors. Use encoder and gyro\n"
"#   feedback to compensate.\n"
"# =========================================================================\n"
"\n"
"import uct_mouse\n"
"import math\n"
"\n"
"TICK_DIST_M = (2.0 * math.pi * 0.031) / 8.0\n"
"\n"
"def drive_straight(distance_m):\n"
"    \"\"\"\n"
"    TODO: Implement closed-loop straight line control.\n"
"    Use encoder counts to measure distance, and gyroscope Z-axis angular rate\n"
"    (gyro) to correct heading drift.\n"
"    \"\"\"\n"
"    print(f\"Driving straight for {distance_m}m...\")\n"
"    # Student code here\n"
"    # Example (open-loop, prone to errors):\n"
"    # uct_mouse.set_motors(50, 50)\n"
"    # uct_mouse.delay_ms(1500)\n"
"    # uct_mouse.set_motors(0, 0)\n"
"    pass\n"
"\n"
"def turn_left_90():\n"
"    \"\"\"\n"
"    TODO: Implement closed-loop turning control.\n"
"    Use the gyroscope Z-axis angular rate (gyro) to integrate heading angle\n"
"    and turn exactly 90 degrees counter-clockwise.\n"
"    \"\"\"\n"
"    print(\"Turning 90 degrees left...\")\n"
"    # Student code here\n"
"    # Example (open-loop, prone to errors):\n"
"    # uct_mouse.set_motors(-35, 35)\n"
"    # uct_mouse.delay_ms(600)\n"
"    # uct_mouse.set_motors(0, 0)\n"
"    pass\n"
"\n"
"def run_square():\n"
"    if not uct_mouse.init():\n"
"        print(\"Initialization failed.\")\n"
"        return\n"
"\n"
"    # Load polarity calibration if it exists\n"
"    try:\n"
"        with open(\"polarity.txt\", \"r\") as f:\n"
"            lines = f.read().strip().split(\",\")\n"
"            uct_mouse.set_polarity(int(lines[0]), int(lines[1]))\n"
"    except Exception:\n"
"        uct_mouse.set_polarity(1, 1)\n"
"\n"
"    print(\"--- Milestone 1: Run a Square ---\")\n"
"\n"
"    for side in range(4):\n"
"        # 1. Drive forward 1 meter\n"
"        drive_straight(1.0)\n"
"        \n"
"        # 2. Settle briefly\n"
"        uct_mouse.set_motors(0, 0)\n"
"        uct_mouse.delay_ms(200)\n"
"        \n"
"        # 3. Turn 90 degrees left\n"
"        turn_left_90()\n"
"        \n"
"        # 4. Settle briefly\n"
"        uct_mouse.set_motors(0, 0)\n"
"        uct_mouse.delay_ms(200)\n"
"\n"
"    print(\"Milestone 1 Completed!\")\n"
"\n"
"if __name__ == \"__main__\":\n"
"    run_square()\n"
;
#endif
