#include "pikaScript.h"
#include "uct_mouse_Mouse.h" // Auto-generated by the Rust pre-compiler
#include "micromouse_kernel.h"
#include "stm32l4xx_hal.h"

// Expose the raw hardware polling functions from the C Kernel
extern void refreshADCs(void);
extern void refreshSWValues(void);
extern void refreshTOFValues(void);
extern void refreshIMUValues(void);
extern void refreshINA219Values(void);
extern void serial_interface_tick(void);

// This function is automatically bound to Python's `mouse.set_pwm(left, right)`
void uct_mouse_Mouse_set_pwm(PikaObj *self, int left, int right) {
    kernel_set_pwm((int16_t)left, (int16_t)right);
}

int uct_mouse_Mouse_get_tof_l(PikaObj *self) {
    return kernel_get_state()->tof_l;
}

int uct_mouse_Mouse_get_tof_r(PikaObj *self) {
    return kernel_get_state()->tof_r;
}

void uct_mouse_Mouse_tick(PikaObj *self) {
    // 1. Force the C hardware to physically poll the sensors
    refreshADCs();
    refreshSWValues();
    refreshTOFValues();
    refreshIMUValues();
    refreshINA219Values();
    
    // 2. Keep the OLED screen and USB JSON telemetry active!
    kernel_update_display();
    serial_interface_tick(); 
    
    // 3. Pace the Python loop to ~20Hz
    HAL_Delay(50);
}