#include "pikaScript.h"
#include "micromouse_kernel.h"
#include "stm32l4xx_hal.h"

// Expose internal PikaScript API for building tuples
extern PikaObj* New_pikaTuple(void);
extern Arg* arg_newInt(int64_t val);

// Expose the raw hardware polling functions so the Python thread can yield to them
extern void refreshADCs(void);
extern void refreshSWValues(void);
extern void refreshTOFValues(void);
extern void refreshIMUValues(void);
extern void refreshINA219Values(void);
extern void serial_interface_tick(void);

// These prototypes match the uct_mouse.h generated by the Rust Pre-compiler

int uct_mouse_init(PikaObj *self) {
    // The hardware is already initialized by main.c, so we just return success
    return 1;
}

void uct_mouse_set_motors(PikaObj *self, int left_pwm, int right_pwm) {
    kernel_set_pwm(left_pwm, right_pwm);
}

PikaObj* uct_mouse_get_tof(PikaObj *self) {
    const KernelState_t* s = kernel_get_state();
    PikaObj* tuple = New_pikaTuple();
    pikaList_append(tuple, arg_newInt(s->tof_l));
    pikaList_append(tuple, arg_newInt(s->tof_al));
    pikaList_append(tuple, arg_newInt(s->tof_c));
    pikaList_append(tuple, arg_newInt(s->tof_ar));
    pikaList_append(tuple, arg_newInt(s->tof_r));
    return tuple;
}

PikaObj* uct_mouse_get_encoders(PikaObj *self) {
    const KernelState_t* s = kernel_get_state();
    PikaObj* tuple = New_pikaTuple();
    pikaList_append(tuple, arg_newInt(s->lenc));
    pikaList_append(tuple, arg_newInt(s->renc));
    return tuple;
}

pika_float uct_mouse_get_gyro(PikaObj *self) {
    return kernel_get_state()->gyro;
}

pika_float uct_mouse_get_vbatt(PikaObj *self) {
    return kernel_get_state()->v_batt;
}

void uct_mouse_delay_ms(PikaObj *self, int ms) {
    // Because we are running bare-metal without an RTOS, a blocking Python delay 
    // would starve the C-Kernel. Instead, we use this delay to pump the hardware!
    uint32_t start_time = HAL_GetTick();
    while ((HAL_GetTick() - start_time) < ms) {
        refreshADCs();
        refreshSWValues();
        refreshTOFValues();
        refreshIMUValues();
        refreshINA219Values();
        kernel_update_display();
        serial_interface_tick();
        HAL_Delay(10); // Prevent 100% CPU hogging during the loop
    }
}

void uct_mouse_set_polarity(PikaObj *self, int left, int right) {
    kernel_set_polarity(left, right);
}

PikaObj* uct_mouse_get_line_sensors(PikaObj *self) {
    const KernelState_t* s = kernel_get_state();
    PikaObj* tuple = New_pikaTuple();
    pikaList_append(tuple, arg_newInt(s->ir_fl));
    pikaList_append(tuple, arg_newInt(s->ir_fr));
    pikaList_append(tuple, arg_newInt(s->ir_sl));
    pikaList_append(tuple, arg_newInt(s->ir_sr));
    return tuple;
}

void uct_mouse_dump_logs(PikaObj *self) {
    extern void kernel_logger_dump(void);
    kernel_logger_dump();
}