#ifndef STUDENT_CODE_H
#define STUDENT_CODE_H
const char* student_python_code = 
"# =========================================================================\n"
"# IMPORTANT NOTE FOR STUDENTS:\n"
"# On the physical microcontroller (bare-metal), sensor values (ToF, encoders, \n"
"# battery) are refreshed inside uct_mouse.delay_ms(). If you write a loop \n"
"# that reads sensors without calling delay_ms(), the values will NEVER update \n"
"# and the program will lock up. Always include a uct_mouse.delay_ms(...) call \n"
"# in your control loops!\n"
"# =========================================================================\n"
"\n"
"\n"
"import uct_mouse\n"
"\n"
"# Initialize connection to either the PC Simulator or Physical Hardware\n"
"uct_mouse.init()\n"
"\n"
"# Load custom motor polarities from config file if present\n"
"try:\n"
"    with open(\"polarity.txt\", \"r\") as f:\n"
"        lines = f.read().strip().split(\",\")\n"
"        left_pol = int(lines[0])\n"
"        right_pol = int(lines[1])\n"
"        uct_mouse.set_polarity(left_pol, right_pol)\n"
"        print(\"[Boot] Loaded motor polarity: Left={}, Right={}\".format(left_pol, right_pol))\n"
"except Exception:\n"
"    # Default to normal polarity if file not found\n"
"    uct_mouse.set_polarity(1, 1)\n"
"\n"
"print(\"--- UCT Mouse is ALIVE! ---\")\n"
"\n"
"while True:\n"
"    print(\"Motors ON\")\n"
"    uct_mouse.set_motors(50, 50)\n"
"    uct_mouse.delay_ms(1000)\n"
"    \n"
"    print(\"Motors OFF\")\n"
"    uct_mouse.set_motors(0, 0)\n"
"    uct_mouse.delay_ms(1000)"
;
#endif
