/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdLib\r\n");
    pika_platform_printf("pikascript-core\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import PikaStdLib\n"
            "import uct_mouse\n"
            "print('=== UCT Micromouse Wall Follower (Standalone) ===')\n"
            "mouse = uct_mouse.Mouse()\n"
            "BASE_SPEED = 40\n"
            "Kp = 0.5  \n"
            "while True:\n"
            "    # 1. Instruct the C-Kernel to fire sensors & sleep 50ms\n"
            "    mouse.tick()\n"
            "    \n"
            "    # 2. Read sensors natively\n"
            "    tof_l = mouse.get_tof_l()\n"
            "    tof_r = mouse.get_tof_r()\n"
            "    \n"
            "    # 3. Calculate error\n"
            "    error = tof_l - tof_r\n"
            "    correction = int(error * Kp)\n"
            "    \n"
            "    # 4. Apply correction\n"
            "    left_speed = BASE_SPEED - correction\n"
            "    right_speed = BASE_SPEED + correction\n"
            "    \n"
            "    # Clamp speeds explicitly (safe for lightweight Python engines)\n"
            "    if left_speed > 100: left_speed = 100\n"
            "    if left_speed < 0: left_speed = 0\n"
            "    if right_speed > 100: right_speed = 100\n"
            "    if right_speed < 0: right_speed = 0\n"
            "    \n"
            "    # 5. Actuate & Log\n"
            "    mouse.set_pwm(left_speed, right_speed)\n"
            "    print('L:', tof_l, '| R:', tof_r, '| Err:', error)\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

