/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdLib\r\n");
    pika_platform_printf("pikascript-core\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "# =========================================================================\n"
            "# IMPORTANT NOTE FOR STUDENTS:\n"
            "# On the physical microcontroller (bare-metal), sensor values (ToF, encoders, \n"
            "# battery) are refreshed inside uct_mouse.delay_ms(). If you write a loop \n"
            "# that reads sensors without calling delay_ms(), the values will NEVER update \n"
            "# and the program will lock up. Always include a uct_mouse.delay_ms(...) call \n"
            "# in your control loops!\n"
            "# =========================================================================\n"
            "import uct_mouse\n"
            "# Initialize connection to either the PC Simulator or Physical Hardware\n"
            "uct_mouse.init()\n"
            "# Default to normal polarity (1, 1). If you need to reverse a motor's polarity,\n"
            "# you can change the values here (e.g., uct_mouse.set_polarity(-1, 1))\n"
            "uct_mouse.set_polarity(1, 1)\n"
            "print(\"--- UCT Mouse is ALIVE! ---\")\n"
            "while True:\n"
            "    print(\"Motors ON\")\n"
            "    uct_mouse.set_motors(50, 50)\n"
            "    uct_mouse.delay_ms(1000)\n"
            "    \n"
            "    print(\"Motors OFF\")\n"
            "    uct_mouse.set_motors(0, 0)\n"
            "    uct_mouse.delay_ms(1000)\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

