/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdLib\r\n");
    pika_platform_printf("pikascript-core\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import uct_mouse\n"
            "print(\"Initializing Micromouse API...\")\n"
            "uct_mouse.init()\n"
            "# Ensure motors and LEDs are stopped initially\n"
            "uct_mouse.set_motors(0, 0)\n"
            "uct_mouse.set_led(0, 0)\n"
            "uct_mouse.set_led(1, 0)\n"
            "uct_mouse.set_led(2, 0)\n"
            "print(\"Running Milestone 0 LED range test. Press SW1 (User Button) to start wall-following.\")\n"
            "is_wall_following = 0\n"
            "side = 0\n"
            "target_dist = 0\n"
            "while True:\n"
            "    # Read TOF sensors\n"
            "    tof = uct_mouse.get_tof()\n"
            "    tof_l = tof[0]\n"
            "    tof_c = tof[2]\n"
            "    tof_r = tof[4]\n"
            "    \n"
            "    # Always run LED Range Test\n"
            "    val0 = 0\n"
            "    if tof_l < 200:\n"
            "        val0 = 1\n"
            "    uct_mouse.set_led(0, val0)\n"
            "    val1 = 0\n"
            "    if tof_c < 200:\n"
            "        val1 = 1\n"
            "    uct_mouse.set_led(1, val1)\n"
            "    val2 = 0\n"
            "    if tof_r < 200:\n"
            "        val2 = 1\n"
            "    uct_mouse.set_led(2, val2)\n"
            "    \n"
            "    # Check if button is pressed (SW1 returns 1 when pressed)\n"
            "    if is_wall_following == 0:\n"
            "        btn_pressed = uct_mouse.get_button()\n"
            "        if btn_pressed == 1:\n"
            "            print(\"SW1 Pressed! Initiating wall-following...\")\n"
            "            # Decide side to follow based on closer wall\n"
            "            if tof_l < tof_r:\n"
            "                side = 1\n"
            "                target_dist = tof_l\n"
            "                print(\"Following LEFT wall\")\n"
            "            else:\n"
            "                side = 2\n"
            "                target_dist = tof_r\n"
            "                print(\"Following RIGHT wall\")\n"
            "            is_wall_following = 1\n"
            "            # Debounce delay\n"
            "            uct_mouse.delay_ms(200)\n"
            "    if is_wall_following == 1:\n"
            "        # Check for collision front wall\n"
            "        if tof_c < 150:\n"
            "            print(\"Front obstacle detected! Stopping wall-following.\")\n"
            "            uct_mouse.set_motors(0, 0)\n"
            "            is_wall_following = 0\n"
            "            # Debounce delay to prevent immediate re-trigger\n"
            "            uct_mouse.delay_ms(500)\n"
            "            \n"
            "        # Drive straight, correcting distance to side wall\n"
            "        if is_wall_following == 1:\n"
            "            if side == 1:\n"
            "                error = target_dist - tof_l\n"
            "                corr = error * 0.4\n"
            "                l_pwm = int(85 + corr)\n"
            "                r_pwm = int(85 - corr)\n"
            "            else:\n"
            "                error = target_dist - tof_r\n"
            "                corr = error * 0.4\n"
            "                l_pwm = int(85 - corr)\n"
            "                r_pwm = int(85 + corr)\n"
            "                \n"
            "            # Clamp PWM values to safe limits\n"
            "            if l_pwm < 75:\n"
            "                l_pwm = 75\n"
            "            if l_pwm > 100:\n"
            "                l_pwm = 100\n"
            "            if r_pwm < 75:\n"
            "                r_pwm = 75\n"
            "            if r_pwm > 100:\n"
            "                r_pwm = 100\n"
            "            \n"
            "            uct_mouse.set_motors(l_pwm, r_pwm)\n"
            "    # Call delay_ms to keep C kernel tick active and allow background VCP commands to process\n"
            "    uct_mouse.delay_ms(50)\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

