/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdLib\r\n");
    pika_platform_printf("pikascript-core\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "# =========================================================================\n"
            "# UCT Micromouse - Milestone 1: Run a Square (1m x 1m) (Framework)\n"
            "# =========================================================================\n"
            "# ASSIGNMENT DESCRIPTION:\n"
            "# Implement a control loop to drive the mouse in a 1 meter by 1 meter square,\n"
            "# turning 90 degrees at each corner, and returning to the start position.\n"
            "# \n"
            "# KEY CONTROLS:\n"
            "# - uct_mouse.set_motors(left_pwm, right_pwm) -> Set speed (-100 to 100)\n"
            "# - uct_mouse.get_encoders() -> Returns (left_ticks, right_ticks)\n"
            "# - uct_mouse.get_tof()      -> Returns (left_mm, center_mm, right_mm)\n"
            "# - uct_mouse.delay_ms(ms)   -> Suspends execution and updates sensors\n"
            "#\n"
            "# GRADING:\n"
            "# - The autograder applies 8% motor imbalance and 8% wheel slip.\n"
            "# - Open-loop timing alone will accumulate errors. Use encoder and gyro\n"
            "#   feedback to compensate.\n"
            "# =========================================================================\n"
            "import uct_mouse\n"
            "import math\n"
            "TICK_DIST_M = (2.0 * math.pi * 0.031) / 8.0\n"
            "def drive_straight(distance_m):\n"
            "    print(f\"Driving straight for {distance_m}m...\")\n"
            "    # Student code here\n"
            "    # Example (open-loop, prone to errors):\n"
            "    # uct_mouse.set_motors(50, 50)\n"
            "    # uct_mouse.delay_ms(1500)\n"
            "    # uct_mouse.set_motors(0, 0)\n"
            "    pass\n"
            "def turn_left_90():\n"
            "    print(\"Turning 90 degrees left...\")\n"
            "    # Student code here\n"
            "    # Example (open-loop, prone to errors):\n"
            "    # uct_mouse.set_motors(-35, 35)\n"
            "    # uct_mouse.delay_ms(600)\n"
            "    # uct_mouse.set_motors(0, 0)\n"
            "    pass\n"
            "def run_square():\n"
            "    if not uct_mouse.init():\n"
            "        print(\"Initialization failed.\")\n"
            "        return\n"
            "    # Load polarity calibration if it exists\n"
            "    try:\n"
            "        with open(\"polarity.txt\", \"r\") as f:\n"
            "            lines = f.read().strip().split(\",\")\n"
            "            uct_mouse.set_polarity(int(lines[0]), int(lines[1]))\n"
            "    except Exception:\n"
            "        uct_mouse.set_polarity(1, 1)\n"
            "    print(\"--- Milestone 1: Run a Square ---\")\n"
            "    for side in range(4):\n"
            "        # 1. Drive forward 1 meter\n"
            "        drive_straight(1.0)\n"
            "        \n"
            "        # 2. Settle briefly\n"
            "        uct_mouse.set_motors(0, 0)\n"
            "        uct_mouse.delay_ms(200)\n"
            "        \n"
            "        # 3. Turn 90 degrees left\n"
            "        turn_left_90()\n"
            "        \n"
            "        # 4. Settle briefly\n"
            "        uct_mouse.set_motors(0, 0)\n"
            "        uct_mouse.delay_ms(200)\n"
            "    print(\"Milestone 1 Completed!\")\n"
            "if __name__ == \"__main__\":\n"
            "    run_square()\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

