#include "stm32l4xx_hal.h"
#include "serial_interface.h"
#include "micromouse_kernel.h"
#include "pikaScript.h"
#include <stdarg.h>
#include <stdio.h>
#include <string.h>

extern void MX_DMA_Init(void);
extern void MX_GPIO_Init(void);
extern void MX_TIM1_Init(void);
extern void MX_TIM3_Init(void);
extern void MX_TIM4_Init(void);
extern void MX_TIM5_Init(void);
extern void MX_TIM7_Init(void);
extern void MX_USART1_UART_Init(void);
extern void MX_NVIC_Init(void);
extern void MX_ADC1_Init(void);
extern void MX_I2C1_Init(void);
extern void MX_I2C2_Init(void);

extern void initMicroMouse(void);
extern void SystemClock_Config(void);

// Expose the raw hardware polling functions to bypass Jesse's screen updates
extern void refreshADCs(void);
extern void refreshSWValues(void);
extern void refreshTOFValues(void);
extern void refreshIMUValues(void);
extern void refreshINA219Values(void);
extern void refreshMotors(void);

extern UART_HandleTypeDef huart1;

// Provide a weak fallback for the Python module bytecode array.
// If the Rust pre-compiler successfully packs main.py, its definition will override this.
// If it fails (which happens on some Mac versions), this prevents the linker from crashing!
__attribute__((weak)) const unsigned char pikaModules_py_a[] = "";

// -------------------------------------------------------------
// Route Python print() statements directly to the USB Serial Port
// -------------------------------------------------------------
void pika_platform_printf(char *fmt, ...) {
    char buf[128];
    va_list args;
    va_start(args, fmt);
    int len = vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    if (len > 0) {
        HAL_UART_Transmit(&huart1, (uint8_t*)buf, len, 100);
    }
}

// -------------------------------------------------------------
// Hardware Fault Handler
// -------------------------------------------------------------
void Error_Handler(void) {
    __disable_irq();
    while (1) {}
}

int main(void) {
    // 1. Core Initialization
    if (HAL_Init() != HAL_OK) { Error_Handler(); }
    
    SystemClock_Config();
    SystemCoreClockUpdate(); // Sync HAL global variables with physical clock

    // 2. Peripheral Initialization
    MX_DMA_Init();
    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_I2C1_Init();
    MX_I2C2_Init();
    MX_TIM1_Init();
    MX_TIM3_Init();
    MX_TIM4_Init();
    MX_TIM5_Init();
    MX_TIM7_Init();
    MX_USART1_UART_Init();
    MX_NVIC_Init();

    // Configure UART for standard 80 MHz APB clock (80,000,000 / 115200 = 694)
    __HAL_UART_DISABLE(&huart1);
    USART1->BRR = 694; 
    __HAL_UART_ENABLE(&huart1);

    // 4. Initialize Hardware Sensors & Actuators
    initMicroMouse();

    // 5. Start Delta-Shadow Network Proxy
    serial_interface_init(&huart1);

    // 6. Initialize PikaScript Embedded Python
    // This automatically executes the auto-generated byte-array of main.py
    // located in pikascript-api/pikaScript.c
    PikaObj *pikaMain = pikaScriptInit();
    

    while (1) {
        refreshADCs();
        refreshSWValues();
        refreshTOFValues();
        refreshIMUValues();
        refreshINA219Values();

        kernel_update_display();
        serial_interface_tick();
    }
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart) {
    serial_interface_rx_callback(huart);
}

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
    // Hijack TIM6 to advance HAL timebase while muting legacy ghost telemetry
    if (htim->Instance == TIM6) {
        HAL_IncTick();
        kernel_watchdog_tick();
    }
}